### ISSUE TITLE
About login Button errors

### ISSUE THREAD

**Issue by Briley0205** [Danilo-Ko/Momentum#1]
두 가지 레포지토리를 비교하고 한 가지 발견한 것은,
첫 번째(exercise) repository 에는 input type="button"을 채택하고,
두 번째(momentom) repository 에는 input type="submit"을 썼다는 것 입니다

**Comment by Danilo-Ko** [comment]
@Briley0205 둘 다 submit을 쓰지 않았나요?

**Comment by Briley0205** [comment]
@Danilo-Ko 음, 보니까 input type="button" value="Log In" / 으로 되어있던걸요?^^
제 생각엔 아마 그 당시(맨 처음 레포지토리를 만들었을 땐) 이런 식으로 만들 생각이셨던 것 같아요~
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/button

**Comment by Briley0205** [comment]
그런데, 어떤 심경의 변화가 있었는지, 두 번째 레포지토리를 만들 땐,
이런 식의 버튼을 만드시려 했었던 것 같아요~
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/submit

**Comment by Danilo-Ko** [comment]
@Briley0205 
todolist &lt;input type = "button" value = "Log In" />
Momentum &lt;input type="submit" class="login-out" value = "Log In" />

여기 이 차이가 있었군요. ㅋ
심경의 변화는 아니고 전에 배운 거랑 니꼬쌤이 가르쳐 준 거랑 믹스가 되어서 아마 그렇게 했나 봅니다. submit를 써야 했는데 안썼네요. 저는 JS 쪽만 봐서 왜 똑 같은데 안돼지 그랬습니다. 
아이고 감사합니다. 시간도 많이 들었을 것 같은데.

**Comment by Briley0205** [comment]
form에서 button 태그가 있으면 따로 부가설정 하지 않아도 제출 버튼 역할을 하게 되지만,
input인 경우, submit 설정이 필요하고, input에 button 타입을 부여하면, 
다른 이벤트를 위한 버튼으로 인식하게 되나봐요🤓

**Comment by Briley0205** [comment]
저도 참, 이렇게 만들어서 배포해 놓고,
잊어버리고 있었나 봐요☆⌒(*＾-゜)v
https://bibley.herokuapp.com/auth/email_login

**Comment by Danilo-Ko** [comment]
@Briley0205 제가 배우기로 submit을 하게 되면 엔터키를 누르던 버튼을 누르던 동작하는 이벤트라고 배웠거든요. 그래서 submit을 썼던 건데 html 쪽에 문제가 있는 줄은 미처 몰랐네요.

**Comment by Danilo-Ko** [comment]
@Briley0205 상당히 이쁘게 만드셨네요. 그런데 님의 만드신 아래와 같은 것은 어떻게 보지요? 주소를 공유해주시기 전에는 제가 볼 수 없는 거죠? 그리고 이 링크에는 또 어떻게 들어가야 하나요? 시도를 했는데 안 들어가네요. ㅋhttps://bibley.herokuapp.com/auth/email_login

**Comment by Danilo-Ko** [comment]
@Briley0205 상당히 이쁘게 만드셨네요. 그런데 님의 만드신 아래와 같은 것은 어떻게 보지요? 주소를 공유해주시기 전에는 제가 볼 수 없는 거죠? 그리고 이 링크에는 또 어떻게 들어가야 하나요? 시도를 했는데 안 들어가네요. ㅋhttps://bibley.herokuapp.com/auth/email_login

**Comment by Danilo-Ko** [comment]
@Briley0205 정해진 e-mail 과 password가 있나보죠?

**Comment by Briley0205** [comment]
@Danilo-Ko 아니요, 이건 진짜 데이터베이스와 백엔드가 있는 사이트라,
이미 가입된 유저들 중에, 해당 e-mail 과 password를 가진 유저가 있는지
확인하는 절차가 있어요

**Comment by Briley0205** [comment]
로그인 하려면 우선 계정을 만들어야 하는 곳이에요.
계정 만드는 곳(Join 하는 곳)은 여기 입니다⬇
https://bibley.herokuapp.com/auth/email_join

**Comment by Danilo-Ko** [comment]
@Briley0205 멋지군요. 지금은 시간이 안되니 (챌린지 숙제를 해야해서. ㅋ) 나중에 둘러 보겠습니다. 다른 repository도 방문해 보고 싶네요.

**Comment by Briley0205** [comment]
언제든지 환영이에요! 챌린지 하다가 잘 안 풀리는 에러 있으면
같이 얘기해요!! 혼자 고민하는 것보다 나을 겁니다💌

**Comment by Danilo-Ko** [comment]
> @Danilo-Ko 아니요, 이건 진짜 데이터베이스와 백엔드가 있는 사이트라, 이미 가입된 유저들 중에, 해당 e-mail 과 password를 가진 유저가 있는지 확인하는 절차가 있어요

와! 저는 데이터베이스와 백엔드까지 다루시면 프론트엔드와 백엔드 둘 다 하실 줄 아시는 건가요? 생초보인 입장에서 이 repository가 대단해 보입니다. 이 repository 제목이 유튜브 클론이라고 나오는데 유튜브 클론을 하면 데이터베이스와 백엔드도 같이 다루어 주나요?

**Comment by Danilo-Ko** [comment]
@Briley0205 그런데 다른 repository를 보려면 어떻게 해야 하나요? 님이 제 것을 가져가셨던 것처럼 제가 fork 해서 웹사이트 주소를 만들어 열었는데 에러가 나네요. 그런 식으로 하는 게 아닌가 보네요? ㅋ

**Comment by Briley0205** [comment]
@Danilo-Ko 메일을 방금 열어봐서 답장이 온 줄 몰랐어요.💤
네, 유튜브 클론 강의에선 프론트엔드와 백엔드, 그리고 데이터 베이스까지 해서
유튜브처럼 동영상 관리 및 유저 로그인 관련 (기초) 보안이나,
댓글관리 등,
관련 데이터베이스를 다루는 과정을 거칩니다ヾ(•ω•`)o

**Comment by Briley0205** [comment]
> @Briley0205 그런데 다른 repository를 보려면 어떻게 해야 하나요? 님이 제 것을 가져가셨던 것처럼 제가 fork 해서 웹사이트 주소를 만들어 열었는데 에러가 나네요. 그런 식으로 하는 게 아닌가 보네요? ㅋ

어제 커스텀 도메인 설정을 마쳐서, 유튜브 클론과 관련된 레포지토리에 깃헙 페이지가 올라와 있을 겁니다. 거기서 웹 사이트를 구경하셔도 되고,
repository에 프로젝트 관련 회고록도 올려놨으니, 한 번 읽어보셔도 괜찮을 겁니다.(아직 다 작성한 것은 아니지만요;;)

**Comment by Briley0205** [comment]
정확히 어떤 식으로 구경하려 하시는 건지는 잘 모르겠지만,
제 프로필 들어가시면 코드나 프로젝트가 보일 겁니다😉

**Comment by Danilo-Ko** [comment]
> 정확히 어떤 식으로 구경하려 하시는 건지는 잘 모르겠지만, 제 프로필 들어가시면 코드나 프로젝트가 보일 겁니다😉

예. 그냥 전반적으로 어떻게 웹페이지들을 만드셨나 구경하려고요. 이런 식으로 다른 분이 만든 것을 구경한 적이 거의 없어서요. 감사합니다.
